Souf-Project/Souf-BE

build.gradle, src/main/java/com/souf/soufwebsite/domain/chat/entity/Chat.java, src/main/java/com/souf/soufwebsite/domain/feed/entity/Feed.java, src/main/java/com/souf/soufwebsite/domain/file/controller/FileController.java, src/main/java/com/souf/soufwebsite/domain/file/dto/FileDto.java, src/main/java/com/souf/soufwebsite/domain/file/entity/File.java, src/main/java/com/souf/soufwebsite/domain/file/entity/FileType.java, src/main/java/com/souf/soufwebsite/domain/file/repository/FileRepository.java, src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java, src/main/java/com/souf/soufwebsite/domain/notification/entity/Notification.java, src/main/java/com/souf/soufwebsite/domain/post/entity/Post.java, src/main/java/com/souf/soufwebsite/domain/user/entity/RoleType.java, src/main/java/com/souf/soufwebsite/domain/user/entity/User.java, src/main/java/com/souf/soufwebsite/global/common/BaseEntity.java, src/main/java/com/souf/soufwebsite/global/config/S3Config.java, src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
📌 진행 이슈
close #9 
기본 엔티티 클래스 및 패키지 구성
=> [Feat] 패키지 구성

.github/workflows/CI-CD.yml, Dockerfile, docker-compose.yml, src/main/java/com/souf/soufwebsite/global/common/HealthCheckController.java, src/main/java/com/souf/soufwebsite/global/common/HeathCheckController.java, src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
EC2에 자동화된 배포를 진행합니다.
- close #39 
1. Docker 파일 생성
2. CI-CD.yml 생성
3. 권한별 접근 가능한 API 설정
=> [Feat] ci cd 파이프라인 구축

src/main/java/com/souf/soufwebsite/domain/member/controller/MemberApiSpecification.java, src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java, src/main/java/com/souf/soufwebsite/domain/member/controller/auth/AuthController.java, src/main/java/com/souf/soufwebsite/domain/member/dto/TokenDto.java, src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java, src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
로그인 시 반환값에 memberId, username, roletype 도 함께 반환되도록 수정했습니다.
authcontroller 에 대한 스웨거 추가되었습니다.
- close #56 
- ![image](https://github.com/user-attachments/assets/50cf1878-f8ce-463f-965c-d9179f120887)
=> [FIX] 로그인 반환값 추가

src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitPopularityResDto.java, src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitReqDto.java, src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitResDto.java, src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitSimpleResDto.java, src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java, src/main/java/com/souf/soufwebsite/domain/recruit/entity/RegionType.java, src/main/java/com/souf/soufwebsite/domain/recruit/entity/WorkType.java, src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java
- close #65 
1.  공고문 업로드 생성 시 최소/최대 금액 및 업무형태 필드 추가
2. 인기있는 공고문 조회 시 데드라인 추가 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
=> [Fix] 공고문 crud 기능 수정

docker-compose.yml, src/main/resources/application.yml
인스턴스 내에 rabbitmq 사용을 위해 yml 파일들을 수정했습니다.
- close #94 
=> [Fix] 채팅 보안 설정

src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatController.java, src/main/java/com/souf/soufwebsite/domain/chat/controller/ChatRoomController.java, src/main/java/com/souf/soufwebsite/domain/chat/dto/ChatMessageResDto.java, src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedDetailResDto.java, src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/member/controller/MemberController.java, src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/MemberResDto.java, src/main/java/com/souf/soufwebsite/domain/member/repository/MemberCustomRepositoryImpl.java, src/main/java/com/souf/soufwebsite/domain/member/service/FavoriteServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/member/service/MemberService.java, src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java
각 채팅 메시지 마다 날짜와 시간을 반환하도록 추가하였습니다.
- close #96 
-<img width="506" alt="image" src="https://github.com/user-attachments/assets/a4cd6d3d-2786-4b18-971c-41463d9f6a94" />
=> [Feat] 채팅 기능 반환값 구체화

src/main/java/com/souf/soufwebsite/domain/chat/repository/ChatRoomNativeRepository.java, src/main/resources/application.yml
채팅 상대방의 profile image url을 가져오기 위해 native query를 수정하였습니다.
- close #98 
=> [Feat] 채팅방 프로필 이미지 출력

build.gradle, src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedResDto.java, src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/file/controller/FileApiSpecification.java, src/main/java/com/souf/soufwebsite/domain/file/controller/FileController.java, src/main/java/com/souf/soufwebsite/domain/file/controller/FileUploadSuccessMessage.java, src/main/java/com/souf/soufwebsite/domain/file/dto/S3UploadPartsDetailDto.java, src/main/java/com/souf/soufwebsite/domain/file/dto/S3VideoUploadSignedUrlReqDto.java, src/main/java/com/souf/soufwebsite/domain/file/dto/VideoResDto.java, src/main/java/com/souf/soufwebsite/domain/file/dto/VideoUploadCompletedDto.java, src/main/java/com/souf/soufwebsite/domain/file/entity/MediaType.java, src/main/java/com/souf/soufwebsite/domain/file/service/FileService.java, src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java, src/main/java/com/souf/soufwebsite/global/config/S3Config.java
- close #93 
1. S3를 v1에서 v2로 변경
2. 피드 업로드 시 동영상도 같이 업로드 될 수 있도록 구현
=> [Feat] 동영상 업로드 로직 추가

docker-compose.yml
=> fix: docker-compose redis 설정 삭제

.github/workflows/CI-CD.yml, .github/workflows/test-CI-CD.yml, docker-compose.yml, src/main/java/com/souf/soufwebsite/domain/member/dto/ReqDto/MemberIdReqDto.java, src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitApiSpecification.java, src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java, src/main/java/com/souf/soufwebsite/domain/recruit/entity/Recruit.java, src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitService.java, src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/main/resources/application-test.yml, src/main/resources/application.yml
- close #113 
1. 공고문 마감 기능을 구현
2. test서버에 대한 CI-CD 기능을 구축하였습니다.
- dev 브랜치에 push가 감지될 때마다 test_CI-CD를 수행하도록 하였습니다.
- yml을 분리하여 필요한 DB를 꺼내어 사용할 수 있도록 하였습니다.
=> [Feat] 공고문 마감 기능 구현

.github/workflows/test-CI-CD.yml
=> fix: test-CI-CD yml 수정

src/main/java/com/souf/soufwebsite/domain/file/entity/MediaType.java, src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
=> Feat/#121/채팅으로 전송할 파일 양식 추가

src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedSimpleResDto.java, src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java, src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitCustomRepositoryImpl.java, src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitRepository.java, src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
인기 피드 조회 return 값 추가
인기 공고문 조회 recruitable 반영
인기 공고문 조회 cityDetail 수정
- close #123
- ![image](https://github.com/user-attachments/assets/dddf3f85-ff70-43cb-89cf-a1edb46b527d)
- ![image](https://github.com/user-attachments/assets/201edfda-aeae-475b-b078-60b81abed456)
- ![image](https://github.com/user-attachments/assets/48890aae-3dd6-4f2f-9c7c-5259cd1ff168)
=> [Fix] 인기 피드  및 공고문 조회 수정

build.gradle, src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java, src/main/java/com/souf/soufwebsite/domain/file/entity/MediaType.java, src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java, src/main/java/com/souf/soufwebsite/global/redis/service/DistributedLockService.java, src/main/java/com/souf/soufwebsite/global/slack/SlackConstant.java, src/main/java/com/souf/soufwebsite/global/slack/service/SlackService.java, src/main/resources/application-prod.yml
- close #143 
1. 특정 이벤트(ex. 회원가입, 게시글 생성 등) 발생 시  슬랙에서 이를 즉각적으로 확인할 수 있도록 Slack과 연동하였습니다.
2. 동영상 타입에 QUICKTIME을 추가하였습니다.
해당 클래스는 이벤트가 발생할 때, SlackBot을 통해 메시지를 전송합니다.
=> Feat: slack 연동하기

src/main/java/com/souf/soufwebsite/domain/feed/controller/FeedController.java, src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java, src/main/java/com/souf/soufwebsite/domain/member/service/MemberServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java, src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
- close #146 
1. SlackBot 메시지를 좀 더 디테일하게 변경
2. 동영상 확장자에 따른 contentType 설정
=> Fix: 동영상 파일 contenttype 수정

src/main/java/com/souf/soufwebsite/domain/feed/service/FeedConverter.java, src/main/java/com/souf/soufwebsite/domain/file/dto/MediaResDto.java, src/main/java/com/souf/soufwebsite/domain/file/service/S3UploaderService.java
- close #154 
동영상 썸네일만 공개하는 범위를 수정하였습니다.
=> Fix: 동영상 썸네일 조회 범위 수정

build.gradle, src/main/java/com/souf/soufwebsite/domain/opensearch/service/IndexingService.java, src/main/java/com/souf/soufwebsite/domain/opensearch/service/InitialIndexingService.java, src/main/java/com/souf/soufwebsite/domain/opensearch/service/SearchService.java, src/main/java/com/souf/soufwebsite/global/config/OpenSearchConfig.java, src/main/java/com/souf/soufwebsite/global/config/OpenSearchInitializer.java, src/main/java/com/souf/soufwebsite/global/config/OpenSearchRestTemplateConfig.java
오픈서치 권한 설정 방식 변경
- close #148
- Opensearch 인증 방식을 마스터 계정 생성 방식에서 sigV4 인증 방식으로 수정
=> [Fix] 오픈서치 권한 설정 방식 변경

src/main/java/com/souf/soufwebsite/domain/comment/entity/Comment.java, src/main/java/com/souf/soufwebsite/domain/comment/repository/CommentCustomRepository.java, src/main/java/com/souf/soufwebsite/domain/comment/repository/CommentCustomRepositoryImpl.java, src/main/java/com/souf/soufwebsite/domain/comment/repository/CommentRepository.java, src/main/java/com/souf/soufwebsite/domain/comment/service/CommentServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/feed/entity/Feed.java, src/main/java/com/souf/soufwebsite/domain/feed/repository/LikedFeedRepository.java, src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
- close #159 
1. 조회 시에 fetch Join이 되지 않아 낭비되는 작업을 방지하고, 게시글이 사라질 시에 댓글도 함께 사라지도록 양방향 매핑관계를 추진하였습니다.
2. 피드 좋아요 확인 여부를 새로운 쿼리를 만들어 분별할 수 있도록 하였습니다.
=> Refactor: 피드 추가 기능 구현

src/main/java/com/souf/soufwebsite/domain/feed/service/FeedServiceImpl.java
Reverts Souf-Project/Souf-BE#175
=> Revert "[Fix] getFeeds currentUser 삭제"

src/main/java/com/souf/soufwebsite/global/config/SecurityConfig.java
complete-signup 컨트롤러 보안 해제
- close #178 
=> [Fix] securityConfig 수정

src/main/resources/application.yml
clienSecret -> clientSecret 오타 수정
- close #183
상세히 구현한 내용들을 기입해 주세요!
=> [Fix] clientSecret 오타 수정

src/main/java/com/souf/soufwebsite/domain/feed/repository/FeedRepository.java, src/main/java/com/souf/soufwebsite/domain/member/dto/ResDto/AdminPostResDto.java, src/main/java/com/souf/soufwebsite/domain/member/service/admin/AdminServiceImpl.java, src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitRepository.java
- close #189 
관리자 페이지의 게시글 리스트 조회 기능 구현 완료
=> Feat: 관리자 페이지 구현

src/main/java/com/souf/soufwebsite/domain/member/controller/admin/AdminController.java, src/main/java/com/souf/soufwebsite/domain/report/dto/ReportReqDto.java, src/main/java/com/souf/soufwebsite/domain/report/entity/Report.java, src/main/java/com/souf/soufwebsite/domain/report/entity/ReportReason.java, src/main/java/com/souf/soufwebsite/domain/report/entity/ReportStatus.java, src/main/java/com/souf/soufwebsite/domain/report/exception/ErrorType.java, src/main/java/com/souf/soufwebsite/domain/report/exception/NotMatchedReportOwnerException.java, src/main/java/com/souf/soufwebsite/domain/report/repository/ReportCustomRepositoryImpl.java, src/main/java/com/souf/soufwebsite/domain/report/service/ReportService.java, src/main/java/com/souf/soufwebsite/domain/report/service/ReportServiceImpl.java
- #192 
1. 게시글 신고 생성 기능 구현
2. 관리자 페이지 게시글 조회 기능 수정
=> Feat: 신고 기능 구현

src/main/java/com/souf/soufwebsite/domain/feed/dto/FeedSimpleResDto.java, src/main/java/com/souf/soufwebsite/domain/recruit/controller/RecruitController.java, src/main/java/com/souf/soufwebsite/domain/recruit/dto/RecruitPopularityResDto.java, src/main/java/com/souf/soufwebsite/domain/recruit/repository/RecruitRepository.java, src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitScheduledService.java, src/main/java/com/souf/soufwebsite/domain/recruit/service/RecruitServiceImpl.java
- #209 
클라이언트가 요청한 인기 피드/공고문에 필드 추가
- 인기 피드에는 피드 제목을 추가
- 인기 공고문에는 사용자 이름 및 프로필, 공고문에 대한 최소, 최대 금액을 추가하였습니다.
=> Fix: 인기 피드 response 값 수정
